version: '3.8'

services:
  angular-app:
    build:
      context: ./front
      dockerfile: Dockerfile
    ports:
      - "4200:80"
    depends_on:
      - spring-boot-app
    networks:
      - app-network

  spring-boot-app:
    build:
      context: ./back
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge